#!/usr/bin/env bash
# Print the sensor's nftables ruleset.
#
#   render-nftables.sh ADMIN_PORT "PLATFORM_IP, PLATFORM_IP"
#
# Policy (docs/threat-model.md):
# - inbound: honeypot (22 -> Cowrie on 2222), admin sshd on ADMIN_PORT, DHCP; nothing else
# - outbound: DROP everything new, except the cloud platform's own addresses
#   (DHCP / VM agent / metadata; never DNS). The `maintenance` chain is filled
#   only by egress-window during updates, with Cowrie stopped.
set -euo pipefail

admin_port="${1:?admin port}"
platform_ips="${2:-}"

if ! [[ $admin_port =~ ^[0-9]+$ ]] || (( admin_port < 1024 || admin_port > 65535 )) \
   || (( admin_port == 2222 )); then
  echo "ADMIN_PORT must be 1024-65535 and not 2222" >&2
  exit 1
fi
if [[ -n $platform_ips ]] && ! [[ $platform_ips =~ ^[0-9.,\ ]+$ ]]; then
  echo "PLATFORM_IPS must be IPv4 addresses separated by commas" >&2
  exit 1
fi

platform_rule=""
if [[ -n $platform_ips ]]; then
  platform_rule="ip daddr { ${platform_ips} } accept"
fi

cat <<EOF
#!/usr/sbin/nft -f
# Generated by render-nftables.sh. Edit that script, not this file.
flush ruleset

table inet sensor {
    chain prerouting {
        type nat hook prerouting priority dstnat; policy accept;
        # Attackers connect to 22; Cowrie listens unprivileged on 2222.
        tcp dport 22 redirect to :2222
    }

    chain input {
        type filter hook input priority filter; policy drop;
        iif "lo" accept
        ct state established,related accept
        ct state invalid drop
        tcp dport 2222 accept comment "honeypot"
        tcp dport ${admin_port} accept comment "admin sshd; source IP limited by the cloud firewall"
        udp dport 68 accept comment "DHCP replies"
        icmp type { echo-request, destination-unreachable, time-exceeded } limit rate 10/second accept
        icmpv6 type { nd-neighbor-solicit, nd-neighbor-advert, nd-router-advert, destination-unreachable, packet-too-big, time-exceeded } accept
    }

    chain output {
        type filter hook output priority filter; policy drop;
        oif "lo" accept
        ct state established,related accept comment "replies to inbound connections"
        jump maintenance
        meta l4proto { tcp, udp } th dport 53 drop comment "no DNS outside maintenance"
        ${platform_rule}
        udp dport 67 accept comment "DHCP"
        icmpv6 type { nd-neighbor-solicit, nd-neighbor-advert, nd-router-solicit } accept
        limit rate 6/minute log prefix "sensor-egress-drop: " level info
    }

    # Empty except while an egress window is open (see egress-window).
    chain maintenance {
    }

    chain forward {
        type filter hook forward priority filter; policy drop;
    }
}
EOF
