#!/usr/bin/env bash
# Provision a Cowrie SSH honeypot sensor on a fresh Ubuntu 24.04 VM.
#
#   sudo bash setup-sensor.sh         # reads ./sensor.env (see sensor.env.example)
#
# Run it from your first SSH session (port 22). At the end:
#   - the real sshd moves to $ADMIN_PORT (key-only); port 22 goes to Cowrie
#   - nftables drops all new outbound traffic (see render-nftables.sh)
#   - a 15-minute rollback timer is armed. Reconnect on $ADMIN_PORT and run
#     `sudo sensor-confirm`, or the firewall and sshd changes are undone.
# Safe to re-run.
set -euo pipefail

here="$(cd "$(dirname "$0")" && pwd)"
env_file="${SENSOR_ENV:-$here/sensor.env}"

log() { printf '\n==> %s\n' "$*"; }
die() { echo "error: $*" >&2; exit 1; }

[[ $EUID -eq 0 ]] || die "run as root (sudo)"
[[ -f $env_file ]] || die "missing $env_file (copy sensor.env.example and fill it in)"
# shellcheck source=/dev/null
source "$env_file"

: "${ADMIN_USER:?set ADMIN_USER in sensor.env}"
: "${ADMIN_PORT:?set ADMIN_PORT in sensor.env}"
: "${PULL_PUBKEY:?set PULL_PUBKEY in sensor.env}"
: "${COWRIE_HOSTNAME:?set COWRIE_HOSTNAME in sensor.env}"
: "${COWRIE_SSH_VERSION:?set COWRIE_SSH_VERSION in sensor.env}"
COWRIE_TAG="${COWRIE_TAG:-v3.0.15}"
PLATFORM_IPS="${PLATFORM_IPS-168.63.129.16, 169.254.169.254}"
LOG_RETENTION_DAYS="${LOG_RETENTION_DAYS:-14}"

id "$ADMIN_USER" >/dev/null 2>&1 || die "ADMIN_USER '$ADMIN_USER' does not exist"
[[ -s "$(getent passwd "$ADMIN_USER" | cut -d: -f6)/.ssh/authorized_keys" ]] \
  || die "$ADMIN_USER has no authorized_keys; you would be locked out"
[[ $PULL_PUBKEY =~ ^(ssh-ed25519|ecdsa-sha2-nistp256|ssh-rsa)\ [A-Za-z0-9+/=]+( .*)?$ ]] \
  || die "PULL_PUBKEY does not look like an SSH public key"
[[ $COWRIE_HOSTNAME =~ ^[a-z][a-z0-9-]{1,30}$ ]] || die "COWRIE_HOSTNAME: lowercase letters, digits, dashes"
[[ $COWRIE_HOSTNAME != svr04 ]] || die "svr04 is Cowrie's default hostname and a known fingerprint"
[[ $COWRIE_SSH_VERSION =~ ^SSH-2\.0-[[:print:]]+$ ]] || die "COWRIE_SSH_VERSION must start with SSH-2.0-"
[[ $COWRIE_TAG =~ ^v[0-9]+\.[0-9]+\.[0-9]+$ ]] || die "COWRIE_TAG must look like v3.0.15"
[[ $LOG_RETENTION_DAYS =~ ^[0-9]+$ ]] || die "LOG_RETENTION_DAYS must be a number"
# Validates ADMIN_PORT and PLATFORM_IPS as a side effect.
nft_rules="$(bash "$here/render-nftables.sh" "$ADMIN_PORT" "$PLATFORM_IPS")"

log "Installing packages (egress is still open at this point)"
export DEBIAN_FRONTEND=noninteractive
apt-get update -q
apt-get upgrade -yq
apt-get install -yq git python3-venv python3-dev build-essential libssl-dev libffi-dev nftables rsync
[[ -x /usr/bin/rrsync ]] || die "/usr/bin/rrsync missing (needed to restrict the log-pull key)"

log "Creating users"
id cowrie >/dev/null 2>&1 || adduser --system --group --home /opt/cowrie --shell /usr/sbin/nologin cowrie
id logpull >/dev/null 2>&1 || adduser --system --group --home /var/lib/logpull --shell /bin/sh logpull
usermod -aG cowrie logpull
install -d -m 0700 -o logpull -g logpull /var/lib/logpull/.ssh
# The pull key can only read the Cowrie log dir: no shell, no forwarding, no writes.
printf 'restrict,command="/usr/bin/rrsync -ro /var/log/cowrie/" %s\n' "$PULL_PUBKEY" \
  > /var/lib/logpull/.ssh/authorized_keys
chown logpull:logpull /var/lib/logpull/.ssh/authorized_keys
chmod 0600 /var/lib/logpull/.ssh/authorized_keys

log "Installing Cowrie $COWRIE_TAG"
install -d -m 0750 -o cowrie -g cowrie /var/log/cowrie /var/lib/cowrie \
  /var/lib/cowrie/downloads /var/lib/cowrie/tty
as_cowrie() { runuser -u cowrie -- "$@"; }
if [[ -d /opt/cowrie/cowrie/.git ]]; then
  as_cowrie git -C /opt/cowrie/cowrie fetch --depth 1 origin "refs/tags/$COWRIE_TAG:refs/tags/$COWRIE_TAG"
  as_cowrie git -C /opt/cowrie/cowrie checkout --quiet "$COWRIE_TAG"
else
  as_cowrie git clone --quiet --depth 1 --branch "$COWRIE_TAG" \
    https://github.com/cowrie/cowrie.git /opt/cowrie/cowrie
fi
[[ -d /opt/cowrie/cowrie-env ]] || as_cowrie python3 -m venv /opt/cowrie/cowrie-env
as_cowrie /opt/cowrie/cowrie-env/bin/pip install --quiet --upgrade pip
as_cowrie /opt/cowrie/cowrie-env/bin/pip install --quiet -r /opt/cowrie/cowrie/requirements.txt
# Build Twisted's plugin cache now; at runtime the code dir is read-only.
as_cowrie env PYTHONPATH=/opt/cowrie/cowrie/src /opt/cowrie/cowrie-env/bin/python -c \
  "from twisted.plugin import IPlugin, getPlugins; list(getPlugins(IPlugin))"

log "Writing Cowrie config"
install -d -m 0750 -o root -g cowrie /etc/cowrie
cat > /etc/cowrie/cowrie.cfg <<EOF
# Generated by setup-sensor.sh. Overrides Cowrie's bundled cowrie.cfg.dist.
[honeypot]
hostname = ${COWRIE_HOSTNAME}
log_path = /var/log/cowrie
state_path = /var/lib/cowrie
download_path = /var/lib/cowrie/downloads
ttylog_path = /var/lib/cowrie/tty
# Cap files attackers upload over SFTP/SCP (downloads fail: no egress).
download_limit_size = 10485760

[ssh]
enabled = true
version = ${COWRIE_SSH_VERSION}
listen_endpoints = tcp:2222:interface=0.0.0.0
# Defaults to true upstream: would let attackers use the sensor as a proxy.
forwarding = false
forward_redirect = false
forward_tunnel = false

[telnet]
enabled = false

[output_jsonlog]
enabled = true
logfile = /var/log/cowrie/cowrie.json
EOF
chown root:cowrie /etc/cowrie/cowrie.cfg
chmod 0640 /etc/cowrie/cowrie.cfg

log "Installing services and helper scripts"
install -m 0644 "$here/cowrie.service" /etc/systemd/system/cowrie.service
install -m 0755 "$here/egress-window" /usr/local/sbin/egress-window
install -m 0755 "$here/sensor-rollback" /usr/local/sbin/sensor-rollback
install -m 0755 "$here/sensor-confirm" /usr/local/sbin/sensor-confirm
cat > /etc/cron.daily/cowrie-retention <<EOF
#!/bin/sh
# Keep ${LOG_RETENTION_DAYS} days of logs on the sensor (they are pulled home long before).
find /var/log/cowrie -name 'cowrie.json.*' -mtime +${LOG_RETENTION_DAYS} -delete
find /var/lib/cowrie/tty -type f -mtime +${LOG_RETENTION_DAYS} -delete
find /var/lib/cowrie/downloads -type f -mtime +7 -delete
EOF
chmod 0755 /etc/cron.daily/cowrie-retention
install -d /etc/systemd/journald.conf.d
printf '[Journal]\nSystemMaxUse=200M\n' > /etc/systemd/journald.conf.d/sensor.conf
# Automatic updates would only fail without egress; update in maintenance windows.
systemctl disable --now apt-daily.timer apt-daily-upgrade.timer 2>/dev/null || true
systemctl daemon-reload
systemctl restart systemd-journald

log "Arming the 15-minute rollback timer"
rm -f /var/lib/sensor/confirmed
systemctl stop sensor-rollback.timer 2>/dev/null || true
systemd-run --quiet --collect --unit=sensor-rollback --on-active=15m /usr/local/sbin/sensor-rollback

log "Moving the real sshd to port $ADMIN_PORT"
cat > /etc/ssh/sshd_config.d/00-sensor.conf <<EOF
# Generated by setup-sensor.sh (first value wins, so this file overrides the rest)
Port ${ADMIN_PORT}
PasswordAuthentication no
KbdInteractiveAuthentication no
PermitRootLogin no
AllowUsers ${ADMIN_USER} logpull
AllowTcpForwarding no
AllowAgentForwarding no
X11Forwarding no
EOF
sshd -t || { rm -f /etc/ssh/sshd_config.d/00-sensor.conf; die "sshd config test failed"; }
# Ubuntu 24.04 starts sshd via ssh.socket, which ignores Port; use the plain service.
systemctl disable --now ssh.socket 2>/dev/null || true
systemctl enable ssh.service
systemctl restart ssh.service

log "Applying the firewall"
printf '%s\n' "$nft_rules" > /etc/nftables.conf
nft -c -f /etc/nftables.conf
systemctl enable nftables
systemctl restart nftables

log "Starting Cowrie"
systemctl enable cowrie
systemctl restart cowrie
sleep 3
systemctl is-active --quiet cowrie || { journalctl -u cowrie -n 30 --no-pager; die "cowrie failed to start"; }

cat <<EOF

Done. Within 15 minutes, from a NEW terminal (keep this one open):

    ssh -p ${ADMIN_PORT} ${ADMIN_USER}@<sensor-ip>
    sudo sensor-confirm

If you can't get in, wait: the rollback timer restores sshd on port 22.
EOF
